version: "3.9"

networks:
  algafood-network:
    driver: bridge

services:
  algafood-mysql:
    image: mysql:8.0
    # caso ocorra erro: Unable to load authentication plugin 'caching_sha2_password'.
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
    ports:
      - "3307:3306"
    networks:
      - algafood-network

  algafood-api:
    build: .
    image: algafood-api    
    #substitui o CMD do docker file
    command: ["/wait-for-it.sh", "algafood-mysql:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      SPRING_PROFILES_ACTIVE: DEV
      DB_HOST_PORT: "algafood-mysql:3306"
      SPRING_DATA_REDIS_HOST: algafood-redis
      SPRING_SESSION_STORE_TYPE: redis
#    ports:
#      - "8080:8080"
    networks:
      - algafood-network
    depends_on:
      - algafood-mysql
#    deploy:
#      replicas: 2  ## o nome algafood-api agora vai ser resolvido para dois ips dentro da rede

